### ISSUE TITLE
Coming soon not working on main page

### ISSUE THREAD

**Issue by Amustache** [epfl-si/wp-plugin-epfl-coming-soon#21]
For https://www.epfl.ch/research/domains/optimization/, when Coming Soon is activated, the home page remains accessible. Attempting to access other pages will correctly redirect to Coming Soon. Tested under Firefox and Opera, also after clearing cookies.

**Comment by ponsfrilus** [comment]
Hello @Amustache, everything looks good from here:
![image](https://user-images.githubusercontent.com/176002/133428638-74e36486-bb8b-48cc-b24b-2a8bb217094f.png)

Can you please try in a private window ?

**Comment by Amustache** [comment]
Seems like it was indeed temporary. Thank you!
